# Generated by Django 4.2.5 on 2023-12-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescanningdocument',
            old_name='barcode_generated',
            new_name='doc_received_count',
        ),
        migrations.RenameField(
            model_name='prescanningdocument',
            old_name='inward_document',
            new_name='pre_scanning_count',
        ),
        migrations.RenameField(
            model_name='prescanningdocument',
            old_name='marking_count',
            new_name='scanning_complete_count',
        ),
        migrations.RemoveField(
            model_name='prescanningdocument',
            name='scanning_count',
        ),
        migrations.AddField(
            model_name='prescanningdocument',
            name='map_type_code',
            field=models.ManyToManyField(blank=True, related_name='prescan_maptype_code', to='core.maptype'),
        ),
        migrations.AddField(
            model_name='prescanningdocument',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescanningdocument',
            name='mis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PreDraftingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('drafting_map_count', models.IntegerField(blank=True, null=True)),
                ('correction_uploading_map_count', models.IntegerField(blank=True, null=True)),
                ('pre_drafting_date', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('district_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predrafting_district_id', to='core.district')),
                ('map_type_code', models.ManyToManyField(blank=True, related_name='predrafting_maptype_code', to='core.maptype')),
                ('taluka_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predrafting_taluka_id', to='core.taluka')),
            ],
            options={
                'verbose_name': 'Pre-Drafting Report',
                'verbose_name_plural': 'Pre-Drafting Report',
            },
        ),
    ]
