# Generated by Django 4.2.5 on 2023-12-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_barcode_generated_prescanningdocument_doc_received_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='drafting_qc_topology',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drafting_topology',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
