# Generated by Django 4.2.5 on 2023-12-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department'),
        ('core', '0003_document_drafting_qc_topology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInventry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('allocated_pc', models.IntegerField(blank=True, null=True)),
                ('allocated_laptop', models.IntegerField(blank=True, null=True)),
                ('agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_inventry_id', to='users.agency')),
            ],
            options={
                'verbose_name': 'Agency Inventry',
                'verbose_name_plural': 'Agency Inventry',
            },
        ),
    ]
