# Generated by Django 4.2.5 on 2024-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_document_barcode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='maptype',
            name='map_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
