# Generated by Django 4.2.5 on 2024-01-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_district_district_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taluka',
            name='taluka_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taluka',
            name='taluka_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
