# Generated by Django 4.2.5 on 2024-01-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_taluka_taluka_code_alter_taluka_taluka_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='village_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
