# Generated by Django 4.2.5 on 2024-01-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_village_village_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatus',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
