# Generated by Django 4.2.5 on 2024-02-02 07:43

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_agency_aadhar_no_alter_agency_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_alter_documentstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gov_approve_agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_approve_agency_id', to='users.agency'),
        ),
        migrations.AddField(
            model_name='document',
            name='gov_pdf_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.gov_dynamic_upload_path),
        ),
        migrations.AddField(
            model_name='document',
            name='gov_qc_assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gov_qc_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gov_qc_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='gov_qc_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='gov_qc_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.gov_dynamic_upload_path),
        ),
    ]
