# Generated by Django 4.2.5 on 2024-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_document_gov_approve_agency_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gov_pdf_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
