# Generated by Django 4.2.5 on 2024-03-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document_gov_pdf_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chk_bel_draft_uploaded',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='document',
            name='chk_bel_gov_draft_qc_approved',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='document',
            name='chk_bel_gov_scan_qc_approved',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='document',
            name='chk_bel_scan_uploaded',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2')], default='0', max_length=2),
        ),
    ]
