# Generated by Django 4.2.5 on 2024-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_document_chk_bel_draft_uploaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('barcode_number', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('bel_current_status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Missing Document',
                'verbose_name_plural': 'Missing Document',
            },
        ),
    ]
