# Generated by Django 4.2.5 on 2024-06-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_agency_aadhar_no_alter_agency_address_and_more'),
        ('core', '0013_missingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shape_agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shape_agency_id', to='users.agency'),
        ),
    ]
