# Generated by Django 4.2.5 on 2024-08-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_document_shape_agency_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonDataMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('assetdata', models.JSONField(blank=True)),
            ],
            options={
                'verbose_name': 'Asset Quetions Answer',
                'verbose_name_plural': 'Asset Quetions Answer',
            },
        ),
        migrations.CreateModel(
            name='KumbhAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('asset_name', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_code', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_desc', models.TextField(blank=True, null=True)),
                ('asset_type', models.CharField(blank=True, choices=[('sanitizedType', 'sanitizedType'), ('tentageType', 'tentageType')], default='', max_length=30)),
                ('vendor', models.CharField(blank=True, choices=[('Vendor 1', 'Vendor 1'), ('Vendor 2', 'Vendor 2'), ('Vendor 3', 'Vendor 3'), ('Vendor 4', 'Vendor 4'), ('Vendor 5', 'Vendor 5'), ('Vendor 6', 'Vendor 6')], default='', max_length=30)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='')),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('geo_latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('geo_longitute', models.CharField(blank=True, max_length=30, null=True)),
                ('sector_no', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Kumbh Asset',
                'verbose_name_plural': 'Kumbh Asset',
            },
        ),
    ]
