# Generated by Django 4.2.5 on 2024-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_jsondatamaster_kumbhasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondatamaster',
            name='asset_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
