# Generated by Django 4.2.5 on 2024-08-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_jsondatamaster_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kumbhasset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
