# Generated by Django 4.2.5 on 2024-08-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_kumbhasset_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kumbhasset',
            name='asset_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
