# Generated by Django 4.2.5 on 2024-09-02 09:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_kumbhasset_asset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='gov_pdf_upload',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models.gov_dynamic_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='gov_qc_upload',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=core.models.gov_dynamic_upload_path),
        ),
    ]
