# Generated by Django 4.2.5 on 2024-09-24 07:39

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_alter_document_gov_pdf_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='toplogy_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.dynamic_toplogy_upload_path),
        ),
        migrations.AddField(
            model_name='document',
            name='topology_assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='topology_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topology_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='topology_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
