# Generated by Django 4.2.5 on 2024-09-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_document_topology_agency_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('complaint_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='data/known_faces')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaint',
            },
        ),
    ]
