# Generated by Django 4.2.5 on 2025-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='digitize_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='qc_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
