# Generated by Django 4.2.5 on 2025-07-03 08:44

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_document_digitize_remarks_document_qc_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TippenDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('tippen_scan_upload', models.FileField(blank=True, null=True, upload_to=core.models.dynamic_scan_upload_path)),
                ('barcode_number', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('district_code', models.CharField(blank=True, max_length=5, null=True)),
                ('village_code', models.CharField(blank=True, max_length=7, null=True)),
                ('taluka_code', models.CharField(blank=True, max_length=7, null=True)),
                ('map_code', models.CharField(blank=True, max_length=5, null=True)),
                ('tippen_uploaded_date', models.DateTimeField(blank=True, null=True)),
                ('tippen_digitize_upload', models.FileField(blank=True, null=True, upload_to=core.models.dynamic_digitize_upload_path)),
                ('tippen_polygon_count', models.IntegerField(blank=True, default=0)),
                ('tippen_digitize_assign_date', models.DateTimeField(blank=True, null=True)),
                ('tippen_digitize_completed_date', models.DateTimeField(blank=True, null=True)),
                ('tippen_qc_upload', models.FileField(blank=True, null=True, upload_to=core.models.dynamic_qc_upload_path)),
                ('tippen_qc_assign_date', models.DateTimeField(blank=True, null=True)),
                ('tippen_qc_completed_date', models.DateTimeField(blank=True, null=True)),
                ('tippen_remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('current_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documentstatus')),
                ('tippen_digitize_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tippendigitize_agency_id', to='users.agency')),
                ('tippen_digitize_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tippendigitizeby_user', to=settings.AUTH_USER_MODEL)),
                ('tippen_qc_agency_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tippenqc_agency_id', to='users.agency')),
                ('tippen_qc_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tippenqcby_user', to=settings.AUTH_USER_MODEL)),
                ('tippen_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tippenby_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tippen Document',
                'verbose_name_plural': 'Tippen Document',
            },
        ),
    ]
