# Generated by Django 4.2.5 on 2025-07-03 08:56

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_tippendocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='tippendocument',
            name='backup_file_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.dynamic_backupfile_upload_path),
        ),
        migrations.AlterField(
            model_name='tippendocument',
            name='tippen_digitize_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.dynamic_tippen_digitize_upload_path),
        ),
        migrations.AlterField(
            model_name='tippendocument',
            name='tippen_qc_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.dynamic_tippen_qc_upload_path),
        ),
        migrations.AlterField(
            model_name='tippendocument',
            name='tippen_scan_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.dynamic_tippen_scan_upload_path),
        ),
    ]
