# Generated by Django 5.2.6 on 2025-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tippendocument_backup_file_upload_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='JsonDataMaster',
        ),
        migrations.DeleteModel(
            name='KumbhAsset',
        ),
        migrations.RenameField(
            model_name='tippendocument',
            old_name='tippen_remarks',
            new_name='tippen_digitize_remarks',
        ),
        migrations.AddField(
            model_name='tippendocument',
            name='tippen_qc_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
