# Generated by Django 5.2.6 on 2025-09-19 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_delete_complaint_delete_jsondatamaster_and_more'),
        ('users', '0004_user_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tippendocument',
            index=models.Index(fields=['district_code'], name='core_tippen_distric_473a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='tippendocument',
            index=models.Index(fields=['village_code'], name='core_tippen_village_49dd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='tippendocument',
            index=models.Index(fields=['taluka_code'], name='core_tippen_taluka__259b7d_idx'),
        ),
        migrations.AddIndex(
            model_name='tippendocument',
            index=models.Index(fields=['map_code'], name='core_tippen_map_cod_a40dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='tippendocument',
            index=models.Index(fields=['current_status'], name='core_tippen_current_8aaa96_idx'),
        ),
        migrations.AddIndex(
            model_name='tippendocument',
            index=models.Index(fields=['district_code', 'taluka_code', 'village_code', 'map_code', 'current_status'], name='core_tippen_distric_d99044_idx'),
        ),
    ]
