# Generated by Django 5.2.6 on 2025-10-29 10:37

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tippendocument_core_tippen_distric_473a2e_idx_and_more'),
        ('users', '0004_user_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tippendocument',
            name='tippen_gov_qc_agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tippengovqc_agency_id', to='users.agency'),
        ),
        migrations.AddField(
            model_name='tippendocument',
            name='tippen_gov_qc_assign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tippendocument',
            name='tippen_gov_qc_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tippengovqcby_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tippendocument',
            name='tippen_gov_qc_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tippendocument',
            name='tippen_gov_qc_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tippendocument',
            name='tippen_gov_qc_upload',
            field=models.FileField(blank=True, null=True, upload_to=core.models.dynamic_tippen_gov_qc_upload_path),
        ),
    ]
