# Generated by Django 4.2.5 on 2023-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(blank=True, related_name='user_department', to='core.department'),
        ),
    ]
